#!/bin/sh
# SPDX-License-Identifier: MIT
# Handle mdev network-interface add/remove events.

set -eu

case "${ACTION:-}" in
    add|"")
        ifconfig "$MDEV" up
        ifup "$MDEV" 2>/dev/null || true
        ;;
    remove)
        ifdown "$MDEV" 2>/dev/null || true
        ;;
esac
