# SPDX-License-Identifier: MIT
USB_HOSTNAME="antsdr"
USB_IPADDR="192.168.2.1"
USB_IPADDR_HOST="192.168.2.10"
USB_NETMASK="255.255.255.0"
USB_ETHERNET_MODE="rndis"
NETWORK_MODE="dhcp"
NETWORK_IPADDR=""
NETWORK_NETMASK="255.255.255.0"
NETWORK_GATEWAY=""
WLAN_SSID=""
WLAN_PASSWORD=""
WLAN_IPADDR=""
XO_CORRECTION=""
UDC_HANDLE_SUSPEND=0
