# SPDX-License-Identifier: MIT
# Keep physical Ethernet and USB gadget Ethernet under the same declarative
# /etc/network/interfaces policy.
usb[0-9]  root:root 660 */usr/lib/antsdr/net-hotplug
eth[0-9]  root:root 660 */usr/lib/antsdr/net-hotplug
