# SPDX-License-Identifier: MIT
# Keep physical Ethernet, USB gadget Ethernet, and removable WLAN interfaces
# under the same declarative /etc/network/interfaces policy.
wlan[0-9] root:root 660 */usr/lib/antsdr/net-hotplug
usb[0-9]  root:root 660 */usr/lib/antsdr/net-hotplug
eth[0-9]  root:root 660 */usr/lib/antsdr/net-hotplug
